#framerate
framerate: 30 
#read=d/f/k; read from data/file/kinect
read: k
#save=y/n
save: n
#directories to load images/test data
path_depth: /media/vassilis/Data/KinectData/Moving Object/Depth
path_color: /media/vassilis/Data/KinectData/Moving Object/Color
#directories to load train data
train_path: /media/vassilis/Data/hand_dataset
#pathname of calibrated image eges
cal_edges_path: Calibration_Edges.jpg
cal_frame_path: Calibration_Frame.jpg
#files to save images
save_depth: Depth
save_color: Color
#save parameters
max_depth_im_num_to_save: 200
# Choose object detection method ( segmentation or noise_model )
detection_method: segmentation
# Variables necessary for object detection by using background noise model
max_contours_num: 3
calib_secs: 2
lowest_pixel_noise_deviation: 0.02
depth_thres: 10
lap_thres: 0.01
running_mean_depth_count: 5
outlier_shape_time: 1.5
#Variables for object detection by scene segmentation
cond_erosions_num: 10
already_segmented_path: AlrSegm.jpg
segmentation_data: SegmData
max_objects_size_ratio: 0.04
#Variables necessary for approximate wrist detection
interp_window: 7
cutoff_angle_ratio: 15
wearing_dist_rate: 0.05
lambda_power_weight: 1
length_ratio_power_weight: 1
length_power_weight: 1.5
num_of_checked_segments: 10
lambda_bound: 0.3
#Show results and where (display,file,no)
results: display

