trained_passive_actions_random_forest_using_3dxypca_features_with_10_estimators: 0
trained_dynamic_actions_svms_using_ghog_features_with_linear_kernel_with_buffer_size_10: 1
trained_dynamic_actions_svms_using_sparsecoded_ghog_features_with_linear_kernel_with_buffer_size_10_sparse_dimension(s)_256: 2
trained_dynamic_actions_svms_using_ghog_zhof_features_with_linear_kernel_with_buffer_size_10: 3
trained_dynamic_actions_svms_using_sparsecoded_ghog_zhof_features_with_linear_kernel_with_buffer_size_10_sparse_dimension(s)_256: 4
trained_dynamic_actions_svms_using_ghog_zhof_features_with_linear_kernel_with_buffer_size_10_with_post_time-pca: 5
trained_dynamic_actions_svms_using_sparsecoded_ghog_zhof_features_with_linear_kernel_with_buffer_size_10_sparse_dimension(s)_256_with_post_time-pca: 6
trained_dynamic_actions_mixed_using_3dxypca_ghog_3dhof_features_with_linear_kernel_with_buffer_size_10: 7
trained_dynamic_actions_svms_using_ghog_features_with_linear_kernel_with_buffer_size_10_with_post_time-pca: 8
trained_dynamic_actions_double_using_3dxypca_ghog_3dhof_features_with_linear_kernel_with_buffer_size_10: 9
trained_dynamic__mixed_using_3dxypca_ghog_3dhof_features__with_buffer_size_10: 10
trained_dynamic_actions_svms_using_ghog_3dhof_features_with_linear_kernel_with_buffer_size_10: 11
trained_dynamic_actions_svms_using_sparsecoded_ghog_3dhof_features_with_linear_kernel_with_buffer_size_10_sparse_dimension(s)_256: 12
trained_dynamic_actions_svms_using_ghog_3dhof_features_with_linear_kernel_with_buffer_size_10_with_post_time-pca: 13
trained_dynamic_actions_svms_using_sparsecoded_ghog_3dhof_features_with_linear_kernel_with_buffer_size_10_sparse_dimension(s)_256_with_post_time-pca: 14
